---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: build
    image: plugins/docker
    settings:
      username: robot$drone
      password:
        from_secret: REGISTRY_PASSWORD
      repo: registry.apps.deustotech.eu/reach/reach-dc
      registry: registry.apps.deustotech.eu
      tags: ${DRONE_BUILD_NUMBER}

  - name: deploy
    image: sinlead/drone-kubectl
    settings:
      kubernetes_server: https://rancher.deustotech.eu/k8s/clusters/c-tfxjq
      kubernetes_token:
        from_secret: SAC_TOKEN
    commands:
      - kubectl apply -f kubernetes/ckan/deployment.yaml