---
kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    username: robot$drone
    password:
      from_secret: REGISTRY_PASSWORD
    repo: registry.apps.deustotech.eu/reach/reach-dc
    registry: registry.apps.deustotech.eu
    tags: latest