apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckan-solr
  labels:
    app: ckan-solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ckan-solr
  template:
    metadata:
      labels:
        app: ckan-solr
    spec:
      securityContext:
        runAsUser: 8983
        runAsGroup: 8983
        fsGroup: 8983
      containers:
        - name: ckan-solr
          image: memaldi/ckan-solr:v2.7.2
          command: ["solr-create"]
          args: ["-c", "ckan", "-d", "/conf"]
          volumeMounts:
            - name: solr-data
              mountPath: /opt/solr/server/solr/ckan
              subPath: solr-data
      volumes:
        - name: solr-data
          persistentVolumeClaim:
            claimName: solr-pvc