apiVersion: apps/v1
kind: Deployment
metadata:
  name: ckan
  labels:
    app: ckan
  namespace: reach-data-catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ckan
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ckan
    spec:
      imagePullSecrets:
        - name: robot
      containers:
        - name: ckan
          # image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          # image: reachincubator/reach-data-catalogue:0.0.8
          image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
          env:
          - name: CKAN_SQLALCHEMY_URL
            valueFrom:
              secretKeyRef:
                key: CKAN_SQLALCHEMY_URL
                name: ckan-secret
          - name: CKAN_STORAGE_PATH
            valueFrom:
              configMapKeyRef:
                key: CKAN_STORAGE_PATH
                name: ckan-config
          - name: CKAN_SOLR_URL
            valueFrom:
              configMapKeyRef:
                key: CKAN_SOLR_URL
                name: ckan-config
          - name: CKAN_REDIS_URL
            valueFrom:
              configMapKeyRef:
                key: CKAN_REDIS_URL
                name: ckan-config
          - name: CKAN_SITE_URL
            valueFrom:
              configMapKeyRef:
                key: CKAN_SITE_URL
                name: ckan-config
          - name: CKAN_DATAPUSHER_URL
            valueFrom:
              configMapKeyRef:
                key: CKAN_DATAPUSHER_URL
                name: ckan-config
          - name: GA_ID
            valueFrom:
              secretKeyRef:
                key: GA_ID
                name: ckan-secret
          volumeMounts:
            - name: ckan-data
              mountPath: /var/lib/ckan
              subPath: ckan-data
            - name: ckan-config
              mountPath: /etc/ckan/default/production.ini
              subPath: production.ini       
      volumes:
        - name: ckan-config
          secret:
            secretName: ckan-secret
            items:
            - key: CKAN_CONFIG
              path: production.ini
        - name: ckan-data
          persistentVolumeClaim:
            claimName: ckan-pvc
